# Copyright Jiaqi Liu
---
name: CI/CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  documentation:
    name: Documentation CI/CD
    outputs:
        outcome: ${{ job.status }}
    continue-on-error: true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: pip install -r docs_requirements.txt
        working-directory: docs
      - name: Build docs
        run: make html
        working-directory: docs
      - name: Deploy docs to GitHub Pages
        # if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          user_name: QubitPi
          user_email: jack20220723@gmail.com

  slack-notification:
    name: Send Slack Notification
    if: ${{ always() }}
    needs: documentation
    uses: QubitPi/hashicorp-aws/.github/workflows/slack-notification.yml@master
    with:
      job-status: ${{ needs.documentation.outputs.outcome }}
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
